### ISSUE TITLE
build.bat show error

### ISSUE THREAD

**Issue by z826540272** [CrendKing/avisynth_filter#10]
“F:\Users\oops\Desktop\avisynth_filter-master\avisynth_filter-master\avisynth_filter\avisynth_filter.sln”(默认 目标)
       (1) ->
       “F:\Users\oops\Desktop\avisynth_filter-master\avisynth_filter-master\avisynth_filter\avisynth_filter.vcxproj”( 默认
       目标) (2) ->
       (ClCompile 目标) ->
         F:\Users\oops\Desktop\avisynth_filter-master\avisynth_filter-master\avisynth_filter\src\pch.h(30,10): fatal er
       ror C1083: 无法打开包括文件: “streams.h”: No such file or directory [F:\Users\oops\Desktop\avisynth_filter-master\avisyn
       th_filter-master\avisynth_filter\avisynth_filter.vcxproj]

    0 个警告
    1 个错误  

C1083: cannot open file “streams.h”

**Comment by CrendKing** [comment]
https://github.com/CrendKing/avisynth_filter/commit/b46eba31b18748cd38e24680cbcdf42a9d435b8d should have addressed this issue
