### ISSUE TITLE
0.7.2 not working with svp MPC HC

### ISSUE THREAD

**Issue by z826540272** [CrendKing/avisynth_filter#11]
CreateScriptEnvironment{}returns nullptr

**Comment by Nuihc88** [comment]
The obvious question to ask here is: What AviSynth version are you using?(It's shown on the Settings tab of the Config screen.)
I encountered same issue yesterday. It was probably caused by incompatibility between new AviSynth Filter and old AviSynth+.

**Comment by chainikdn** [comment]
if you're using "official" build from Github - install Avisynth 3.5**.1**

**Comment by CrendKing** [comment]
I'll update README about the version requirement.
