### ISSUE TITLE
Filter registration broken in 0.7.3

### ISSUE THREAD

**Issue by chainikdn** [CrendKing/avisynth_filter#12]
1. consider 0.7.2 already registered and added to MPC-HC
2. unregister 0.7.2 -> open "external filters" in MPC-HC, see "Avisynth filter <not registered>"
3. register 0.7.3 -> nothing changed in "external filters"
4. "Add filter" -> "Avisynth filter" -> now there're two lines - "Avisynth filter <not registered>" + "Avisynth filter"
5. double-click on newly added one - nothing happens, the property page doesn't open

**Comment by CrendKing** [comment]
Test for me? [AviSynthFilter.zip](https://github.com/CrendKing/avisynth_filter/files/5404222/AviSynthFilter.zip)

**Comment by chainikdn** [comment]
this one works
