### ISSUE TITLE
Wrong (de-)interleaving of rightmost unaligned pixels when bpp=2

### ISSUE THREAD

**Issue by chainikdn** [CrendKing/avisynth_filter#15]
... it must be  `for (int i = remainderStart; i < rowSize; i+=bytesPerComponent)` instead of `for (int i = remainderStart; i < rowSize; ++i)` for interleaving. Deinterleaving looks wrong too.

**Comment by CrendKing** [comment]
Fixed at https://github.com/CrendKing/avisynth_filter/commit/00c2062a8a36b864cf5ff83b25105cb24d63bbf9

I didn't realize I don't have a test for the 2bpp case. Thanks for letting me know.
