### ISSUE TITLE
HDR issue

### ISSUE THREAD

**Issue by z826540272** [CrendKing/avisynth_filter#16]
Can you make it passthrough HDR metadata to SCREEN？
because madvr was high overhead，even with lowest setting.

**Comment by CrendKing** [comment]
What do you mean? Currently the filter just passthrough any HDR data without processing it. And I thought there is a "passthrough to screen" option in madVR right? So can't you just choose that if you use madVR? I don't know what does EVR do with HDR.

**Comment by z826540272** [comment]
because madvr was high overhead,Causes stuttering and errors with SVP，if have a feature like madvr passthrough HDR, then we can improve playback performance with hdr support

**Comment by CrendKing** [comment]
Delivering any data to end device should be the job of either the renderer, or another separate filter. This filter is only focusing on transforming video samples according to AviSynth script. It is wrong to amalgamate unrelated functionality into one place.
