### ISSUE TITLE
install.bat does not work via double click or run as administrator

### ISSUE THREAD

**Issue by mark007** [CrendKing/avisynth_filter#23]
### Environment
Mostly na, Using Windows 10 64bit.

### Describe the bug
When trying to install the plugin via the install.bat, it doesn't work by double clicking on it, or right clicking and running as administrator. The error is 'The module avisynth_filter_64.ax failed to load.'

Instead I need to cd into the directory in an elevated cmd prompt, and run install.bat from there. I can make a patch to resolve this to make it behave similar to the likes of the madVR install.bat, which seems to support running via right click / run as administrator?

### To Reproduce
1. Right click on install.bat
2. Run as Administrator

**Checklist**
- Did you try a different **video player** and check if the issue persist? For example, if your main video player is MPC-HC, try MPC-BE.
Answer: na

- Did you try a different **video renderer** and check if the issue persist? For example, if issue exists with madVR, try EVR.
Answer: na

- Did you try a different **video file** and check if the issue persist? Try another file with different format, dimension and frame rate.
Answer: na

**Comment by CrendKing** [comment]
Does https://github.com/CrendKing/avisynth_filter/commit/224b34c5c02334a2c10b496f4b7d60078b9189d4 fix the problem? If not, I need a better explanation of how to reproduce the issue.

**Comment by mark007** [comment]
Fantastic! That fixed it, I think that's a great improvement. Thanks for such a great filter btw. Looking forward to future updates.
