### ISSUE TITLE
Couldn't install

### ISSUE THREAD

**Issue by Shnxxx** [CrendKing/avisynth_filter#29]
I am using a new laptop and didn't install anything video-related apps yet except LAVFilters, MadVR, and PotPlayer.

### Environment
- Filter version: v0.8.2
- AviSynth+ version: v3.6.1
- OS: Windows 10 x64
- Video player: PotPlayer x64
- Splitter filter and video decoder: LAV Filters
- Video renderer: madVR
- Video format: NV12

### Describe the bug
Couldn't install it.

### To Reproduce

1. Download the .zip file
2. Extract it
3. Run "install.bat" as Administrator.

**Comment by CrendKing** [comment]
Can you follow https://github.com/CrendKing/avisynth_filter/wiki/How-to-enable-logging to enable log, then try [AviSynthFilter.zip](https://github.com/CrendKing/avisynth_filter/files/5620260/AviSynthFilter.zip), then send me the log file?

**Comment by Shnxxx** [comment]
There was no `AviSynthFilter` key in `HKEY_CURRENT_USER\SOFTWARE` but I created one and followed the rest of the instructions. After playing a video no log file was created.

I also did try manually adding the `avisynth_filter_64.ax` by using `Add external filter` but after selecting it, it doesn't appear on the list. I tried adding `MadVR` manually too, thinking that maybe it really doesn't add up, but it appeared on the list.

**Comment by CrendKing** [comment]
I meant to install, observe the error dialog, then send me the generated log. The log file is generate only when some program loads the .ax file. Playing a video without loading it will not generate anything.

Not appearing after "add external filter" could be the same problem as installation fail. Don't mix in video player or any other filter. Let's focus on just avsf.

**Comment by Shnxxx** [comment]
Okay so here's what I've done.

I created the registry value:
![image](https://user-images.githubusercontent.com/48496678/100827075-d2204100-3496-11eb-8350-db9b1724ff1a.png)

Then run the `install.bat` as administrator.
![image](https://user-images.githubusercontent.com/48496678/100827103-e8c69800-3496-11eb-855b-dd4d4bc1f5b0.png)

Then navigate to `C:\` to check the log but no log was generated.

**Comment by CrendKing** [comment]
That screenshot is good enough. Try install the latest Visual C++ runtime libraries: [Direct link](https://aka.ms/vs/16/release/vc_redist.x64.exe), [Download page](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).

**Comment by CrendKing** [comment]
Also note that, if lack of the runtime libraries is the cause, and you only install either x64 or x86 version of the library, you will still get one error (the one you are still missing), because the install script tries to install both versions. But if you don't care about the missing one, just ignore it.

**Comment by Shnxxx** [comment]
>That screenshot is good enough. Try install the latest Visual C++ runtime libraries: Direct link, Download page.

This worked for me! Thank you again!
