### ISSUE TITLE
[LAV Filters] Access Violation

### ISSUE THREAD

**Issue by Disaer** [CrendKing/avisynth_filter#32]
### Environment
- Filter version: v0.8.4
- AviSynth+ version: v3.6.1
- OS: Windows 10 x64 2004
- Video player: [MPC-BE x64 1.5.5.5433, MPC-HC x64 1.9.8
- Splitter filter and video decoder: LAV Filters
- Video renderer: madVR, EVR-CP
- Video format: NV12
- AviSynth script: any
- Do you use other DirectShow filters? Specify name and version: no

### Describe the bug
When using LAV Filters (LAV Splitter Source to be precise) pressing Stop then Play will crash the video player. MPC-BE just closes, MPC-HC shows an Access violation message. AVSF v0.8.2 has no this problem.

![2020-12-09](https://user-images.githubusercontent.com/32884204/101658045-a9c7b200-3a55-11eb-805b-d37b52660639.png)

### To Reproduce

1. Enable **LAV Splitter Source** in MPC-BE and make it prefer (or just start MPC-HC)
2. Open any video, press Stop in video player, and then Play

**Checklist**
- Try a different **video player** and check if the issue persist. For example, if your main video player is MPC-HC, try MPC-BE.
Findings: issue persists

- Try a different **video renderer** and check if the issue persist. For example, if issue exists with madVR, try EVR.
Findings: issue persists

- Try a different **video decoder** and check if the issue persist.
Findings: no problem with MPC-BE internal filters

**Comment by CrendKing** [comment]
Sorry about the regression. Fixed [AviSynthFilter.zip](https://github.com/CrendKing/avisynth_filter/files/5667401/AviSynthFilter.zip)
