### ISSUE TITLE
Source PAR is not respected after frame size change

### ISSUE THREAD

**Issue by chainikdn** [CrendKing/avisynth_filter#39]
looks like changes from https://github.com/CrendKing/avisynth_filter/commit/6a4951b9eddbe0cfb68078f8842b239feacecea6 were lost at some point

**Comment by CrendKing** [comment]
Version to reproduce?

**Comment by chainikdn** [comment]
any version
you're just not using the old PAR value at all

**Comment by CrendKing** [comment]
I remember when I was reviewing your change, I theorized that someone put something like
```
return ColorBars(500, 300)
```
in the avs. I thought using script video's SAR as new DAR made sense.

Also, our results only differ if the original video's SAR is already different to the DAR in vih, i.e. `newBmi->biWidth * newVih2->dwPictAspectRatioY != newBmi->biHeight * newVih2->dwPictAspectRatioX`. You code would scale the DAR by the factor of new_sar / old_sar, while my code simply use new_sar. I don't have any video that meets the prerequisite, so I don't know if this is a right-or-wrong situation.

If you have any video and/or avs script that shows your logic makes more sense, I'm happy to change.

**Comment by chainikdn** [comment]
take a video with PAR != 1.0
imagine a script that do simple crop
what will you see?

**Comment by CrendKing** [comment]
I generated a video which is 1280x720 with some absurd DAR like 5:1, plugin a crop function in avs. I can see your logic would scale the 5:1 DAR to the cropped frames, while my logic would lose that DAR. I think preserving the property of the original video is more important. I'll switch to your logic.
