### ISSUE TITLE
[BUG] Settings don't save.

### ISSUE THREAD

**Issue by Shnxxx** [CrendKing/avisynth_filter#42]
## Environment
Filter version: `v0.9.5`
AviSynth+ version: `3.7.0`
OS: `Windows 10 x64`
GPU: `NVIDIA MX150`
CPU: `INTEL i5-8250u`
Video player: `PotPlayer 201021 (1.7.21311)`
Splitter filter and video decoder: `LAV Filters`
Video renderer: `MadVR`
Video format: `YV12`
AviSynth script: `SVPLite`
Do you use other DirectShow filters? Specify name and version: `No`

#
I tried playing some video using the updated configurations said above and everything works fine. Then I tried changing my Filter and unchecked all unnecessary input formats except `YV12`. Clicked `Apply` and `OK`

Then pressed `Apply` again and `OK` on the PotPlayer. Stopped the video then play it again to restart and make sure that the settings were applied. After that, it throws an error that `Only 8bit sources allowed`. I was confused at first since I unchecked all unnecessary video input formats and just left `YV12` alone. And when I tried to check it, all boxes were checked which I'm pretty sure I unchecked the rest of them except `YV12`.

I tried unchecking them all again and repeated the said above process. It still showed the error and the checkboxes were all checked again.

**Comment by CrendKing** [comment]
Fixed in https://github.com/CrendKing/avisynth_filter/commit/7be27fd0cd530b18718a87d8348fd14f90ba1e06

In the meanwhile, you can manually set the formats in `HKEY_CURRENT_USER\Software\AviSynthFilter`.

Also, you should leave `NV12` on if you use hardware acceleration.
