### ISSUE TITLE
Crash when jumping & 100% hanging when video ends natually

### ISSUE THREAD

**Issue by ssssssbbb** [CrendKing/avisynth_filter#43]
### Environment
- Filter version: https://github.com/CrendKing/avisynth_filter/issues/41#issuecomment-817276763
- AviSynth+ version: 3.7
- OS: Win10 x64 1909
- Video player: Potplayer x64 210318(1.7.21467)
- Splitter filter and video decoder: LAV filter& LAV video decoder 0.74.1.75
- Video renderer: madVR and EVR(CP)
- Video format: NV12
- AviSynth script: SVP4.5.206

- Do you use other DirectShow filters? Specify name and version: No

### Describe the bug
1.Crashes easily when jumping
![114312986-45ae1b00-9b27-11eb-8321-731a573c8812](https://user-images.githubusercontent.com/82156140/114413065-3dfe7d00-9be0-11eb-9143-672ae5791243.png)
2.100% Hangs when the video ends natually

### To Reproduce

1.SVP(GPU)+madVR: crashes easily when jumping, different results depend on videos. 100% hangs when video ends natually
2.SVP(CPU)+madVR: jumping is much more stable, not sure 100% stable.  100% hangs when video ends natually
3.SVP(GPU)+EVR(CP): same as 1
4.SVP(CPU)+EVR(CP): same as 2
5.SVP off+EVR/madVR: same as 2

Note: Restarting SVP is required when switching between CPU and GPU.

**Checklist**
- Try a different **video player** and check if the issue persist. For example, if your main video player is MPC-HC, try MPC-BE.
Findings: MPC-HC(with its internal LAV 0.70) also crashes when jumping, but keep playing till the end.

- Try a different **video renderer** and check if the issue persist. For example, if issue exists with madVR, try EVR.
Findings: see above

- Try a different **video file** and check if the issue persist. Try another file with different format, dimension and frame rate.
Findings: 720P videos crash easier than the 1080P ones.

[hang when  the video ends.log](https://github.com/CrendKing/avisynth_filter/files/6297832/hang.when.the.video.ends.log)
[jumping crash.log](https://github.com/CrendKing/avisynth_filter/files/6297834/jumping.crash.log)

**Comment by ssssssbbb** [comment]
I used the version that I quoted, not the last one cause it couldn't even start playing.

I didn't know this info...I'll try AVS+ 3.5

**Comment by CrendKing** [comment]
OK. Here is a new version that I added git HEAD hash to the filter's version string. You should be able to see it in the settings page as well as the log file.

In settings:
![1](https://user-images.githubusercontent.com/975235/114494799-d0e3eb00-9bd1-11eb-8b76-3d1013734bfc.jpg)

In log file, search for a line like this:
`T   xxxxx @        x: Filter version: 0.9.4 # aab15a2`

[avisynth_filter_64.zip](https://github.com/CrendKing/avisynth_filter/files/6301153/avisynth_filter_64.zip): Version should be exactly `0.9.4 # aab15a2`

**Comment by ssssssbbb** [comment]
No problem so far, even with avs+3.7

I can see the version string in both setting UI and log file, but there is no "debug" in title bar.

**Comment by CrendKing** [comment]
The line with "debug" starts with "Filter in graph: AviSynth Filter". You should find one.

If the crashes no longer happen, please close the issue. If they do, please provide info.

**Comment by ssssssbbb** [comment]
Thanks for the fix. Both aab15a2 and v0.10.0 are OK.
