### ISSUE TITLE
Request support for VapourSynth R45

### ISSUE THREAD

**Issue by Ken1256** [CrendKing/avisynth_filter#48]
R45 is the least problem and most stable version.
*Sorry, it is not an bug, the bug label should be deleted.

**Comment by CrendKing** [comment]
Can you refer to the source where it says R45 is the most stable version? R45 was released 3 years ago. If later versions introduce some problems, shouldn't they be reported and fixed already?

The only version 3.6 API we used is [`getCoreInfo2`](http://www.vapoursynth.com/doc/api/vapoursynth.h.html#getcoreinfo2). After replacing it with `getCoreInfo`, I can verify everything else seems to work. So once we sort out the justification, the fixing is easy.

**Comment by Ken1256** [comment]
R48 starts avx2 optimization in many filters, which leads to some follow-up problems and incompatibility with old scripts.
e.g https://github.com/vapoursynth/vapoursynth/issues/538
I have used R45 for several years and it is very stable. The second stable version is R47 before avx2 optimization.
No one reported any major problems with R45, but people started to report problems after the new avx2 version was released.

**Comment by CrendKing** [comment]
I see, that's valid point. However, as you said, if the filters you use suffer the issue, use R47 which has the new R3.6 API but stable. Unless, there's critical issue that's only introduced in R47?

**Comment by Ken1256** [comment]
Some bug fixed after r48(too long to remember), I will stick on R45.
e.g https://github.com/vapoursynth/vapoursynth/issues/497

**Comment by CrendKing** [comment]
I lowered VapourSynth API version requirement to R3.5

https://github.com/CrendKing/avisynth_filter/commit/be39c27746e8d9d593682011684881c8f2e68354
