### ISSUE TITLE
Just another formats/colors conversion issue

### ISSUE THREAD

**Issue by chainikdn** [CrendKing/avisynth_filter#49]
AVSF ver. 1.0.0
sample 10-bit video: https://mega.nz/file/wJMDjYwI#ZIdVbSxUh3oiPNuiypE__KyT08r6X2OR5TFl1rQ6wkE
no SVP
minimal avs script:
```
AvsFilterSource()
# ConvertBits(8)
```

case 1
1. play video, note selected formats: "in P016 out P016"
2. uncomment "ConvertBits", reload script
3. image corrupted

case 2
1. play video (with ConvertBits already uncommented), everything seems OK
2. BUT - "input YV24 output YV24" - is it an expected behavior?

**Comment by CrendKing** [comment]
I can repro case 1. Interestingly, I can only repro with this specific video file. My other P010 and YV24 files are fine. I'll look into this.

For case 2, I get NV12 (correctly) instead of YV24, even though YV24 is selected in settings.

**Comment by CrendKing** [comment]
Does https://github.com/CrendKing/avisynth_filter/actions/runs/894330652 fix the issue?

**Comment by chainikdn** [comment]
fixed image corruption, yes

for the case 2 - ok, now it tells "Connected with types: in NV12 out NV12"
again, is this expected? shouldn't it feed the script with 10-bit source in any case?

**Comment by CrendKing** [comment]
> I mean, it must be "P010 -> NV12", isn't it?

Fixed typo in https://github.com/CrendKing/avisynth_filter/commit/06d06c358545b231cc06a5ef112f0090502ae96f

> BTW, the build artifacts look strange.

Care to elaborate?

**Comment by chainikdn** [comment]
"Release x64" -- 21.9 MB ?

**Comment by CrendKing** [comment]
2 pdb files are included, each with ~10MB, 21.9MB seems fine. The downloaded zip file is only 5MB though.

**Comment by chainikdn** [comment]
ok, this one looks fixed

FYI the user reports that another issue (which I can't reproduce on my laptop) was also fixed:
![AvisynthFilterIssue02](https://user-images.githubusercontent.com/9394230/120673582-f8ea1f00-c49b-11eb-8ce1-b20f072133e5.png)
