### ISSUE TITLE
Black screen after clean installation

### ISSUE THREAD

**Issue by chainikdn** [CrendKing/avisynth_filter#51]
Just installed clean fresh Window 10 21H1 in a VM, then installed SVP.
After switching from ffdshow to AVSF - it doesn't work at all. The filter is missing from the filters list, player shows black screen.
What am I missing?
[avsf.log](https://github.com/CrendKing/avisynth_filter/files/6602560/avsf.log)

**Comment by CrendKing** [comment]
It looks like registration problem. Does `regsvr32 avisynth_filter_64.ax` give you success result?

**Comment by chainikdn** [comment]
at least the property page works, and it writes the log in runtime

**Comment by CrendKing** [comment]
If property page works, yeah, it should have registered. But never hurt trying, right?

Does the same file have problem on the real machine? It could be some dependency problem (missing C++ runtime, etc) or capability problem (e.g. virtual machine lacks the GPU capacity to do acceleration or madVR rendering).

**Comment by chainikdn** [comment]
it isn't just one particular file but any video
and everything works well via ffdshow raw

**Comment by CrendKing** [comment]
Yes, the sequence is strange, and I think I've saw these before, but I don't know what exactly is the cause. Does AVSF set to have "Preferred" merit? Have you used the "Reset List" button to reset the media types? Try the debug version and see if any assertion pops.

**Comment by chainikdn** [comment]
> Does AVSF set to have "Preferred" merit? Have you used the "Reset List" button to reset the media types? Try the debug version and see if any assertion pops.  EVR?

Yes. Yes. Nothing. Yes, but avsf doesn't want to load with any other renderer too.

**Comment by CrendKing** [comment]
I just spawned a clean virtual machine, refresh install MPC-HC, copied SVP's AviSynth.dll, put AVSF in it and able to play filtered video correctly. I can't test SVP since I have only one SVP license you gave me, but we know SVP is fine, so the problem must be somewhere else?

**Comment by chainikdn** [comment]
More dark magic: I tried today's last build - and it doesn't work as before. 
Then I got latest sources and built them myself, copied to the VM, and guess what? It works.

**Comment by CrendKing** [comment]
Since you can build the filter yourself, you know you can [remote debugging](https://docs.microsoft.com/en-us/visualstudio/debugger/remote-debugging-cpp?view=vs-2019) into the VM guest? Setup that remote tools in guest, load the not working version, and debug from host. Should be easy to get the error message.

**Comment by chainikdn** [comment]
btw, 0.9.4-release works, and 0.10.0-release doesn't

**Comment by chainikdn** [comment]
ok, the case seem closed...
EVR doesn't support anything other than YUY2 in a VirtualBox, cause
> The graphics driver determines which video formats are supported
and 0.10.0-1.1.0 doesn't have that input reconnection logic
> T   4868 @      453: Pins are connected with media types: NV12 -> YUY2
> T   4868 @      453: Attempt to reconnect input pin with media type YUY2

the last build from 'Actions' works
