### ISSUE TITLE
Avisynth Filter doubles playback framerate when used with default potplayer codecs

### ISSUE THREAD

**Issue by chorong761** [CrendKing/avisynth_filter#53]
### Environment
- Filter version: v.1.1.0 #8332de9 (also tried latest commit)
- AviSynth+ version: v3.5 r3106 
- OS: Windows 10 x64 20H2
- AviSynth script: SVP user, but the issue occurs when SVP is not running/program closed
-[avsf log.log](https://github.com/CrendKing/avisynth_filter/files/6641171/avsf.log.log)

### Describe the bug

-When Avisynth Filter is enabled and playing any video using default potplayer codecs, it would result in double framerate even if source is progressive

-Works fine when using LAV video decoder, would have the issue when using built in FFmpeg decoders

### To Reproduce

1. Keep codec settings as default (potplayer v210428 x64, 210611 x64 beta)
2. Add Avisynth Filter to potplayer
3. Play any video

**Comment by CrendKing** [comment]
I can setup locally to generate a almost exact same log file as yours, but I can't reproduce the issue. From what I can see in the log, the timestamps of output frames 1:1 match the source frame, so I should not have the said issue. Could you check PotPlayer settings again? Maybe backup your current and try a clean config?

**Comment by chorong761** [comment]
> I can setup locally to generate an almost exactly same log file as yours, but I can't reproduce the issue. From what I can see in your log, the timestamps of output frames 1:1 match the source frames, so it should not have the said issue. Could you check PotPlayer settings again? Maybe backup your current and try a clean config?

I backed up my config and reset the potplayer settings. video would play at file framerate right at launch, but one I add the filter and restart the video, it plays back at double framerate

**Comment by CrendKing** [comment]
Do you have the problem on every video or only specific? If specific, can you share the info of the video?

**Comment by chorong761** [comment]
> Do you have the problem on every video or only specific? If specific, can you share the info of the video?

No, it happens with all kinds of videos, 23.976, 29.97, 30, interlaced, progressive. 

Here's an video I filmed (sorry for bad quality, didn't want to install capture software) to show the issue.
https://www.youtube.com/watch?v=HzC5_c_et_4

**Comment by CrendKing** [comment]
Thanks for the video. I misunderstood the issue. You were talking about the output fps in OSD. I think that number is not very important. You can change different renderers and have completely different numbers. For example, I have 165Hz display. If I use madVR, that number is 165. If I use the system "Video Renderer", that number is 24. The same happens in MPC-* players.

**Comment by chorong761** [comment]
> Thanks for the video. I misunderstood the issue. You were talking about the output fps in OSD. I think that number is not very important. You can change different renderers and have completely different numbers. For example, I have 165Hz display. If I use madVR, that number is 165. If I use the system "Video Renderer", that number is 24. The same happens in MPC-* players (the stats bottom bar).
> 
> For accurate output FPS from AVSF's perspective, check its status page.

To confirm, I just checked the status in AVSF and it does say 23.976 (which was the source file fps). I think my current issue is a bit different than yours (I also use madvr too and it does show 60fps on 60hz screen also) since in both cases I'm testing with evr-cp, only change was built-in ffmpeg vs lav video decoder. But anyways it looks like it isn't that much of an issue like you said earlier and thank you for you help.

**Comment by CrendKing** [comment]
I know EVR shows double fps. My point is, that number doesn't matter. I don't know how is it calculated, but as long as it never manifest any visible problem, I don't worry about it. The important matter to me is if AVSF's own stats show correct numbers. Since you confirmed it, I'll close the ticket.
