### ISSUE TITLE
Vapoursynth filter performance drop

### ISSUE THREAD

**Issue by ssssssbbb** [CrendKing/avisynth_filter#56]
### Environment
- Filter version: v1.1.2
- Vapoursynth version: R53
- OS: Win10 x64 1909
- AviSynth script: SVP 4.5.210
- Log file[Vapour stutter.log](https://github.com/CrendKing/avisynth_filter/files/6693541/Vapour.stutter.log)

### Describe the bug
FPS dropped when speeding up, it looks stutters. Problems don't come with all videos. 
"fear.the.walking.dead.s06e16.internal.1080p.web.h264-whosnext" stutters.
"Game.of.Thrones.S01E10.2011.BluRay.1080p.DTS.x264-CHD" stutters.
"Spectre.2015.1080p.BluRay.x264-SPARKS" is OK.
You can find them on RARBG.

### To Reproduce

1.Potplayer+madVR/EVR+Vapoursynth filter: open the video, start and play with 1.5x or faster speed, fps drops
2.MPC-HC 1.9.13+ madVR/EVR+Vapoursynth filter:  open the video, start and play with 1.5x or faster speed, fps drops
3.Potplayer+madVR/EVR+Avisynth filter: OK
4.MPC-HC 1.9.13+ madVR/EVR+Avisynth filter:OK

I don't know what the green line means, but it raised with the stutter.
![1](https://user-images.githubusercontent.com/82156140/122911786-3c90c400-d38a-11eb-8cad-929022fdb4f3.jpg)

**Comment by CrendKing** [comment]
1. Do you use any script/SVP?
2. You are saying MPC-HC + madVR +VPSF has the problem. Do you see frames dropped in madVR's OSD? I don't know what's that MPC-HC version in your screenshot. Mine don't have the fancy graphs.
3. For MPC-HC + EVR, there's the "Statistics" section, which should show the dropped frames. Do you see any?

**Comment by ssssssbbb** [comment]
1. Using SVP, the "24fps" on the left bottom is showed occasionally, it's changing, not meaning without FRC. In fact the number on the left top shows it's 68fps.
2. Yes, dropped  frames kept increasing with repeated frames at first for a moment, than stoped, after speeding up for a while it increased again and this time it didn't stop. I'm using MPC-HC 1.9.13, press Ctrl+J(EVR) to show this graph and the data on the left top.
3. Yes as well.

**Comment by CrendKing** [comment]
1. Try to repro the issue with the simplest setup, i.e. no SVP, no PotPlayer, just MPC-XX + VPFS + madVR/EVR. When diagnosing issue, involve as little as components. If SVP is required to repro, then we can focus on SVP.
2. I didn't know about the Ctrl+J OSD. Thanks.
3. Does it drop without speeding? Does it drop with < 1 speed?

**Comment by CrendKing** [comment]
https://github.com/CrendKing/avisynth_filter/actions/runs/962360064 fixed a small issue involving changing playback rate. It's unlikely to have fixed the dropped frames, but worth a try.

**Comment by CrendKing** [comment]
Try https://github.com/CrendKing/avisynth_filter/actions/runs/962360064?

**Comment by ssssssbbb** [comment]
> Try https://github.com/CrendKing/avisynth_filter/actions/runs/962360064?

Made no visuable change.

It's normal without SVP. 

When using madVR with SVP, with 1x speed it sitll drops 1 frame every 2 seconds. With < 1 speed, both EVR and madVR are normal and the graph is OK.

**Comment by CrendKing** [comment]
OK. To summarize, you can get 1 frame drop every 2 seconds with MPC-HC + VPSF + madVR without speed change, consistently? So far this is the simplest setup, so let's focus on this. Is it specific to video file? Is the walking dead one good? Can you provide log file and screenshot (madVR OSD, when dropping frames)?

**Comment by ssssssbbb** [comment]
Frame drops consistently with 3 videos mentioned above, walking dead included.

CPU used 34% and GPU 16%. It doesn't drop frames when playing with 60FPS and origin speed, but drops after speeding like 75FPS.

SVP settings: put them into C:\Users\%username%\AppData\Roaming\SVP4\settings after backing up yours
[settings.zip](https://github.com/CrendKing/avisynth_filter/files/6709142/settings.zip)

1.0 speed log:
[1x.log](https://github.com/CrendKing/avisynth_filter/files/6709123/1x.log)

1.0 speed screenshot:
![1x](https://user-images.githubusercontent.com/82156140/123262386-6680ec80-d52a-11eb-99ba-d7d67f118dac.jpg)

1.5x speed log:
[1.5x.log](https://github.com/CrendKing/avisynth_filter/files/6709126/1.5x.log)

1.5x speed screenshot:
![1 5x](https://user-images.githubusercontent.com/82156140/123262444-77c9f900-d52a-11eb-9125-beaab6cf36e4.jpg)

**Comment by CrendKing** [comment]
I can repro now. This might require some bigger changes.

**Comment by CrendKing** [comment]
Does https://github.com/CrendKing/avisynth_filter/actions/runs/969690201 fix the problem?

**Comment by ssssssbbb** [comment]
Yes ,it works. With normal speed, it doesn't drop 1/2 fps any more. But 1.5x is still stuttering.

But I found something new here. Both AVSF and VPSF still drop frames when playing with normal speed, but much slower than 1/2 fps, it's hard to count, but sometimes it get faster. And I did the test as below:
1.MPC-HC + madVR + SVP 75FPS at 1x speed: dropped frames increases slowly
2.MPC-HC + EVR + SVP 75FPS at 1x speed: dropped frames increases slowly
3.MPC-HC + madVR + SVP 60/72FPS at 1x speed: 0 dropped frames and stuttering is gone wiht 1.5x
4.MPC-HC + EVR + SVP 60/72FPS at 1x speed: 0 dropped frames and stuttering is gone wiht 1.5x

And……I set FRC to 74.9 fps by modifying the profiles.cfg in AppData\Roaming\SVP4\settings, change the value of "fi_target" to 74.9. There is no stuttering even with 2x speed.

**Comment by CrendKing** [comment]
The slow frame drop is probably due to the mismatch between FRC and monitor refresh rate. chainikdn still has that weird 22/7 for your monitor refresh rate.

As long as it's not dropping massively and AVSF and VPSF show the same result, I consider this issue fixed.

**Comment by ssssssbbb** [comment]
Yes, it's refresh rate related, but 25/8 and 22/7 have the same problem. MadVR's OSD shows my refresh rate is 74.923Hz, as long as fps is larger than this it stutters.

BTW, is VPSF better than AVSF? It seems the CPU/GPU usage are lower. Is there any other difference?

**Comment by ssssssbbb** [comment]
OK, v1.13 fixed it completely, perfect!

**Comment by CrendKing** [comment]
> BTW, is VPSF better than AVSF? It seems the CPU/GPU usage are lower. Is there any other difference?

VapourSynth has better concurrency model, supports async request, meaning it requires less thread and buffering to achieve the same performance than AviSynth+. Also, Python is a better language to write scripts.

The difference is most cases would be trivial, as the core idea of the two are the same. But if you have to pick one, VPSF is better in general.

**Comment by ssssssbbb** [comment]
The VPSF stuttering comes with speeding is back, since 3e17039, this time I tried recent versions one by one. Now it need a faster speed to trigger, such as 2.0x.

And...even v1.13, the former pefect version, about 3.5x speed will trigger the stuttering while AVSF is OK with at least 5.0x. 

Maybe my usage is somehow wierd. I used so fast a speed because I'm used to skip some sections by speeding up, but when I slow down, the video is delayed. So it's kind of normal use and it's the indication of performance.

**Comment by CrendKing** [comment]
It is sort of expected. Let me explain.

What https://github.com/CrendKing/avisynth_filter/commit/3e170397e79a2aeebee772df8dc162efee242c74 does is to control the input rate based on how much difference between the actual output rate vs the video's theoretical output rate. For example, if the video is supposed to have 60fps, but you are having 30fps, VPSF will gradually increase input rate until the two number matches, or a threshold is hit. "Slowly" because we don't want temporary hiccups to mess up the input rate.

Increasing play speed basically creates output pressure. It takes time for the rate control to kick in. However, if suddenly you go back to normal speed, the pressure disappears, the rate control will restore back down.

The only way to solve your specific problem is probably setting a large static input buffer. This way you never run of source frames, but also waste resource when you don't super speed the video. I could add that option back for you to try.

**Comment by ssssssbbb** [comment]
I understood the logic now. I'll try that later.

>"Slowly" because we don't want temporary hiccups to mess up the input rate

You said "hiccups" did you mean the one of the player or the global one? As far as I know, mpc-hc always stutters when changing speed, meantime reset the dropped frames to 0, this may be its own way to match this two numbers. So we might not need another way to stop messing?

As to potplayer, it's 100% smooth when changing speed, that's why I like it. But the rate messing problem may exist. So, could this clamp be dynamic, self adaptive? Of course, if it's not a good choice, static or changable static is OK.

**Comment by CrendKing** [comment]
hiccup means something in the background of your system suddenly requires resource to do something. For example, your browser receives a message and start rendering stuff, or caching stuff, using CPU and disk. It could affect how fast the source frames deliver. I don't understand your second sentence. The dropped frame count in the player doesn't matter.

The clamp is dynamic, self adaptive. I'm adding the static for you to test.

**Comment by ssssssbbb** [comment]
I'm a layman. Anyway, thanks!

**Comment by ssssssbbb** [comment]
Solved by increasing MinExtraSourceBuffer to 15 and MaxExtraSourceBuffer to 20.

AVSF is OK without modifing these options.

**Comment by CrendKing** [comment]
If you go to the Status page, you can compare the "Input buffer size" between AVSF and VPSF, after you adjust the extra source buffer. Please let me know if the VPSF one is way higher than AVSF when you can't reduce MinExtraSourceBuffer any further without stuttering.

**Comment by ssssssbbb** [comment]
I set min to 5 (4 causes stuttering) and max to 15. The input buffer size of VPSF is 7, the one of AVSF is 18.

The min and max parameters did nothing to AVSF, the input buffer size is always 18.

**Comment by CrendKing** [comment]
So it proves VPSF requires less resource to have the same performance as AVSF. That 18 is mainly determined by how many prefetcher you use in the avs script.

The parameter has the same effect in both filters. Try raise the min to something like 20, then it might change to something like 23-25.

**Comment by ssssssbbb** [comment]
Yes, but that 18 was expected to be limmited to 15 by the max value, wasn't it?

**Comment by CrendKing** [comment]
No. The "15" is **extra**. AVSF's original "overhead" is already 18, while VPSF is probably 4.

**Comment by ssssssbbb** [comment]
It stutters at 3.0x speed again. Increasing min buffer size to 30 can't even handle, so far I don't know how big it should be.

Is this change related? https://github.com/CrendKing/avisynth_filter/actions/runs/1475957293

BTW, now I am using Vaporsynth R57 and the newest VPSF, SVP 4.5.0.213 solved this https://github.com/CrendKing/avisynth_filter/issues/62

**Comment by ssssssbbb** [comment]
Forget it... it was due to the high video bitrate  which is unnoticable.

**Comment by CrendKing** [comment]
Please try this version: https://github.com/CrendKing/avisynth_filter/actions/runs/1514315473

Revert everything about the extra source buffer in your settings to default. Then set `ExtraSourceDecreaseStep` to 0 (default is 1). This will make the buffer never shrink. Let me know if it fixes the problem. I'll explain why it works.

**Comment by ssssssbbb** [comment]
Sorry for bothering you because it's my problem. Last time I played videos which resolutions are 3840×1600 but have low bitrates and got no problem. I thought 1600 is much smaller than 2160 is the reason(2160P stutters  when speeding), but it turns out the smaller bitrate is the actual reason. So this time, with 30+MBps bitrate, my CPU become the bottleneck.

Anyway I tried, default is 0 for min and 15 for max, that's not enough for the video in this case. But ExtraSourceDecreaseStep = 0  is still better, 1 causes actual buffer size dropping with same min and max value, which forcing me to increase the min value. 0 is visable smoother.

**Comment by CrendKing** [comment]
Yes. Forgot to mention, if you are hardware bottlenecked, you need to raise the max value respectively. The min value only affects the initial state, and since decrease step is 0 now, it should not matter if you are playing a long video.

The reason this works is because when you play in 4x play rate, the input frame rate is way over the average fps stored in the video (e.g. 30fps). VPSF thinks you are over-buffered, so it tries to decrease the extra source buffer to conserve resource, until it reaches 0. Once there, it's only a matter of time when the input rate falls behind the output rate, causing frame drop and jitter.

By setting the decrease step to 0, the buffer never shrinks, so you will always have the buffer for the high play rate. This trick is specifically tailor for your "play fast instead of seek" style. People who like to seek should not do this.

**Comment by ssssssbbb** [comment]
Thanks for the tailoring!!

**Comment by ssssssbbb** [comment]
Emm... Tried another video which doesn't occupy 100% CPU, v1.30 indeedly has better performance than newer versions.

**Comment by CrendKing** [comment]
Please review https://github.com/CrendKing/avisynth_filter/wiki/Configuration. You might want to change some setting names.

**Comment by ssssssbbb** [comment]
> Please review https://github.com/CrendKing/avisynth_filter/wiki/Configuration. You might want to change some setting names.

It works, thanks!
