### ISSUE TITLE
Import error from a UTF8 path via RC

### ISSUE THREAD

**Issue by chainikdn** [CrendKing/avisynth_filter#57]
Error message received back via RC is good:
> Import: couldn't open 'C:\Users\Дмитрий\AppData\Roaming\SVP4\scripts\a13335d4.avs

while the yellow on-screen text contains non-alpha characters.

Interesting enough that it works OK if the **log file** is specified in registry.
Also works with a fixed script (not via RC).
Something about encoding conversion initialization?

**Comment by chainikdn** [comment]
https://github.com/CrendKing/avisynth_filter/blob/313004747de3ddbd0cd18c12f1ffd991e9cc4fad/filter_common/src/environment.cpp#L36

**Comment by CrendKing** [comment]
[Fixed](https://github.com/CrendKing/avisynth_filter/commit/5dd45fc51babfcff697e7b63ca9c1d2fa0fd80dd). But if someone puts their SVP directory in non-ASCII path, the dll load will fail, no?
