### ISSUE TITLE
1.30 script error

### ISSUE THREAD

**Issue by ssssssbbb** [CrendKing/avisynth_filter#62]
### Environment
- Filter version: 83eda5d and 1.30
- VapourSynth version: R55-API4~R56
- OS:Win10 x64 1909
- AviSynth script: SVP4
- Python:3.9.7
- Log:[log.log](https://github.com/CrendKing/avisynth_filter/files/7258789/log.log)

Starts playing, it shows script error in both Potplayer and MPC-HC, as the screenshot below, meantime SVP4 shows the video is paused. The video plays at 30fps.
![1](https://user-images.githubusercontent.com/82156140/135439056-850a98cf-4ce4-4160-93c3-2c32673d93bc.png)

**Comment by CrendKing** [comment]
It's [removed](https://github.com/vapoursynth/vapoursynth/commit/cc287f6533e95696ce6f1dd2e29d71a9cfe06aeb#diff-b5f2f3a1864e911d9f45d183fd5468dc759abaf0d63a5abb12801cbaeee892a0), which has been deprecated for over 2 years. Use `vapoursynth.core` instead.

**Comment by ssssssbbb** [comment]
Indeed it comes from SVP. I solved it by replacing "get_core()" with "core" and disabling remote control in VPSF.

By the way, is it different from using SVP?

**Comment by CrendKing** [comment]
What is different from using SVP? Having vs not having SVP remote control VPSF? A script is a script. VPSF doesn't distinguish if it comes from RC or from a static file. The benefit of SVP is that it can dynamically adjust the script according to your setting. If you never need to change during playback, then you can live without RC.

**Comment by ssssssbbb** [comment]
Understood.
