### ISSUE TITLE
 ddfi-vapoursynth

### ISSUE THREAD

**Issue by Usulyre** [CrendKing/avisynth_filter#64]
Environment

    Filter version: 1.3.1 vapoursynth 64 bit version
    VP version: R57 64 bit and python 3.99 64 bit
    OS: win 10 x64 pro
    VP script:
    -Player: MPC-BE 1.6.1 64 bit portable
    -Vapoursynth script and filter:

     https://github.com/syniox/ddfi-vapoursynth

   Sample script:
  
import vapoursynth as vs
import ddfi_vs
core = vs.core
ret = VpsFilterSource
ret = core.std.AssumeFPS(clip=ret,fpsnum=24000,fpsden=1001)
ddfi_vs.ddfi_mv(clip=ret)
output_ret.set_output()

Bug: Player hangs, after pressing play

Reproduce: Load any video file, not sure if the filter is working right.

**Comment by Usulyre** [comment]
Update script but not working:

import vapoursynth as vs
import ddfi_vs
core = vs.core
ret = VpsFilterSource
ret = core.std.AssumeFPS(clip=ret,fpsnum=24000,fpsden=1001)
ret = ddfi_vs.ddfi_svp(clip=ret)
output_ret = core.resize.Bicubic(clip=ret, format=vs.YUV420P8, matrix_s="709")
output_ret.set_output()

OR:

import vapoursynth as vs
import ddfi_vs
core = vs.core
ret = VpsFilterSource
ret = core.std.AssumeFPS(clip=ret,fpsnum=24000,fpsden=1001)
ret = ddfi_vs.ddfi_mv(clip=ret)
output_ret = core.resize.Bicubic(clip=ret, format=vs.YUV420P8, matrix_s="709")
output_ret.set_output()

**Comment by CrendKing** [comment]
First off, [we can't use mvtools](https://github.com/CrendKing/avisynth_filter/issues/61#issuecomment-903191124) as you already know, so I only tested the SVP function. The error I got was that the resize function is throwing error. Once I remove that (seems unneeded), everything looks fine.

I'm not getting any interpolation though, I think due to the (`[1::2]`)[https://github.com/syniox/ddfi-vapoursynth/blob/5f687ee1c9d8a0c179510c78dfdd35eb9afe9187/ddfi_vs.py#L112]. If I remove that, I can see some changes (some frame skips, etc) the script makes, though I don't know what exactly.

**Comment by Usulyre** [comment]
Ok, sorry I forgot about mvtools not working in your filter. 

Can you take a look at this specifically CInterpolate?  Thanks in advance.

http://forum.doom9.org/showthread.php?p=1964712#post1964712

**Comment by CrendKing** [comment]
What about it? If there is problem of using that, please open a new issue with details such as error message and logs. Thanks.

**Comment by CrendKing** [comment]
From the author's comment,

> It takes a MFlowInter clip (iClip parameter) from mvtools2 and replace frames that are duplicate with respect to the previous frame but are not duplicate with respect to the following frame

So in terms of quality it should be just like mvtools2.

**Comment by Usulyre** [comment]
Ok, I did post on that thread, but can it change frame rate? Are there parameters to adjust smoothness, if any? If so, can you show an example besides what the author already posted? Thanks.

**Comment by CrendKing** [comment]
From my understanding of the readme in the download, `CInterpolate` has nothing to do with interpolating unique frames, but to interpolate duplicated frames. I'm not sure what's the benefit of doing that.
