### ISSUE TITLE
Green screen in MPC-BE player with 10bit video

### ISSUE THREAD

**Issue by BlackMickey** [CrendKing/avisynth_filter#65]
### Environment
- Filter version: `v1.3.1 #fa809c3`
- VapourSynth version: `R57 API R4.0`
- OS: Windows 10 x64
- VapoursynthSynth script: SVP 4 Pro
- Log file link: [Vapoursynth Filter Log](https://drive.google.com/file/d/1uvZeQ2DVFpMtWGXrI64e_Vid8yGFJ4so/view?usp=sharing)

### Describe the bug

When using Vapoursynth filter in MPC-BE to play 10Bit video, MPC-BE shows green screen.

### To Reproduce

1. install python 3.9.10
2. install VapourSynth R57
3. install Avisynth filter & VapourSynth Filter v1.3.1
4. [MPC-BE] add filter -> Vapoursynth Filter -> Prefer
5. [Vapoursynth Filter] Enable remote control
6. start svp4 pro
7. play 10bit video

MPC-BE with Avisynth filter
![MPC-BE+Avisynth](https://user-images.githubusercontent.com/45148363/156874408-98524470-e1f3-4a2f-b4a6-3b63006d8983.jpg)

MPC-BE with Vapoursynth filter
![MPC-BE+Vapoursynth](https://user-images.githubusercontent.com/45148363/156874412-c80bdaa7-c064-4615-84da-eb5822e208a6.jpg)

mpv with Vapoursynth
![mpv+Vapoursynth](https://user-images.githubusercontent.com/45148363/156874387-d910d221-c96a-4208-823f-a4a1187372a2.jpg)

**Comment by CrendKing** [comment]
I downloaded the exact same video you showed, tested with my own SVP script and had no problem. Then I extracted SVP's generated script and put in the filter option, still no problem. Finally, I let SVP do the remote injection, and notice it's always in the half-half mode. Though it's different to what you reported here, I'm thinking maybe this is related to SVP having problem with injection for VapourSynth (specifically since VapourSynth recently changed all the API, SVP might have problem with that new version).

**Comment by CrendKing** [comment]
I switched to madVR and there is no long the half-half problem:

![Clipboard 1](https://user-images.githubusercontent.com/975235/157356804-3d87c916-faca-4407-b863-4017de61b20e.jpg)

Try the latest snapshot build here: https://github.com/CrendKing/avisynth_filter/actions/runs/1954868638

If it makes a difference, then we have a clue to look at.

**Comment by CrendKing** [comment]
I downloaded the same video you show here.

I can't reproduce the problem because I don't know how to make SVP output 10 bit video. It always reverts back to NV12 (8 bit), even though I set "Allow 10 bit color depth" to "Always".

**Comment by CrendKing** [comment]
I tried on the same file you show here and have no problem:

![Clipboard 1](https://user-images.githubusercontent.com/975235/157366379-ade1aa4f-0cea-445d-853c-3d9949a78b3c.jpg)

**Comment by BlackMickey** [comment]
I can reproduce it.The problem should be with SmoothFps.

smooth  = core.svp2.SmoothFps(input_m.resize.Point(format=vs.YUV420P16),...)
![YUV420P16](https://user-images.githubusercontent.com/45148363/157692565-a320c48e-a263-44a5-b043-0374d8f9d4ec.png)

smooth  = core.svp2.SmoothFps(input_m.resize.Point(format=vs.YUV420P10),...)
![YUV420P10](https://user-images.githubusercontent.com/45148363/157692499-80615f38-22fb-4f3b-863f-0dffaeea00c2.png)

**Comment by CrendKing** [comment]
Thanks. So you can confirm the problem is the resize with YUV420P10, right? SVP should generate script with YUV420P016 in it, not P010.

Here is the extract of my SVP's generate.js:
```
res += bl+'input_um = clip.resize.'+(media.is420 ? 'Point':'Bicubic')+'(format=vs.YUV420'+(media.p10?'P16':'P8')+',dither_type="'+dither+'")'+br;
```
Check yours. If it is not like this, update your SVP.

**Comment by PhantomGamers** [comment]
I'm having the same issue, but the `SVP 4/script/generate.js` for me has:

```js
res += bl+'input_um = clip.resize.'+(media.is420 ? 'Point':'Bicubic')+'(format=vs.YUV420'+(media.p10?'P10':'P8')+',dither_type="'+dither+'")'+br;
```

my SVP is showing as fully updated on my end hm

**Comment by CrendKing** [comment]
All you need to change is change from `'P10'` to `'P16'`. I'm not sure why we have different content. Maybe I changed that myself earlier and SVP never touched it.

There are two solutions. Either ask SVP to update their generate.js, or I can add a special treatment in the filter for P010, which will incur some performance penalty because it needs to convert all pixels.

**Comment by CrendKing** [comment]
Try the snapshot build from https://github.com/CrendKing/avisynth_filter/actions/runs/1966299497 see if it works.

**Comment by BlackMickey** [comment]
> I'm having the same issue, but the `SVP 4/script/generate.js` for me has:
> 
> ```js
> res += bl+'input_um = clip.resize.'+(media.is420 ? 'Point':'Bicubic')+'(format=vs.YUV420'+(media.p10?'P10':'P8')+',dither_type="'+dither+'")'+br;
> ```
> 
> my SVP is showing as fully updated on my end hm
> 
> EDIT: Replacing the line with yours seems to have fixed the issue though

The generate.js is modified as follows.
 ```js
res += bl+'input_um = clip.resize.'+(media.is420 ? 'Point':'Bicubic')+'(format=vs.YUV420'+(media.p10? global.player=4? 'P16':'P10':'P8')+',dither_type="'+dither+'")'+br;
```

Because 10Bit video is normal in mpv.
