### ISSUE TITLE
x86: crash with ReClock enabled

### ISSUE THREAD

**Issue by chainikdn** [CrendKing/avisynth_filter#7]
no comments - it just crashes on start
call stack shows it's a ReClock's crash when AVSF is enabled, but it doesn't make any difference for the end-user
doesn't crash with ffdshow, obviously

```
 	[External Code]	
>	ReClock.dll!0caeae7d()	Unknown
 	ReClock.dll![Frames below may be incorrect and/or missing, no symbols loaded for ReClock.dll]	Unknown
 	[External Code]	

```

**Comment by CrendKing** [comment]
I'll try, but isn't ReClock obsoleted by madVR, which has the judder removal feature, and supports x64?

**Comment by chainikdn** [comment]
> madVR, which has the judder removal feature

I don't think it's the same thing. However I never used ReClock myself and have no idea why someone uses it now :D Still there's a complain from one user: https://www.svp-team.com/forum/viewtopic.php?pid=76654#p76654

**Comment by CrendKing** [comment]
![Screen](https://user-images.githubusercontent.com/975235/94015541-dbd44c80-fd61-11ea-8840-811e82af4f05.jpg)

Works on my end. ReClock 1.9.0.7, using SVP and doubling frame rate.

Can you try one thing? Re-download AVSF 0.6.1 package. My build yesterday might have some problem.

**Comment by chainikdn** [comment]
ha. it actually crashes IF there's some script set in AVSF, event the simplest "return Info()"

**Comment by CrendKing** [comment]
My script loads SVP and double the frame rate, as you can see in the screenshot.

**Comment by chainikdn** [comment]
it works with empty script path in AVSF + SVP
it crashes with non-empty script path in AVSF, regardless of SVP

**Comment by CrendKing** [comment]
What do you mean "empty script path"? I painted my screenshot to hide the path to the source video.

**Comment by chainikdn** [comment]
by "empty script path" I mean empty "AviSynth script to load" field

**Comment by CrendKing** [comment]
![Screenshot 2](https://user-images.githubusercontent.com/975235/94018976-163fe880-fd66-11ea-9b85-78b6c1fbf959.jpg)

**Comment by chainikdn** [comment]
dunno what else can I say

**Comment by CrendKing** [comment]
Does everything work without ReClock, even include the current "worker" branch? Are we sure ReClock is the cause?

**Comment by CrendKing** [comment]
![Screenshot3](https://user-images.githubusercontent.com/975235/94033231-9a4d9c80-fd75-11ea-8af0-09e9b1e08386.jpg)
![Screenshot4](https://user-images.githubusercontent.com/975235/94033232-9a4d9c80-fd75-11ea-9f05-c8e94bdfd3a2.jpg)

**Comment by chainikdn** [comment]
> Does everything work for you without ReClock, even include the current "worker" branch? 
yep

> Are we sure ReClock is the cause? 
kind of :D

> Does your ReClock have different settings than my screenshot?
nope

> If you want, I can publish a pre-release of the worker branch.
no need... besides, it's hardly usable now cause it hangs on almost every action (for example, change some SVP params)

> FYI, just noticed SVP can only detect playback if I put AviSynth+ 3.6 AviSynth.dll in the MPC directory. 3.5 doesn't work :-p
work for me... there must be something in SVP's log anyway

**Comment by CrendKing** [comment]
> it hangs on almost every action (for example, change some SVP params)
> I don't see huge improvements over regular version

This is the surprise of the day! Where does the difference come from? The new version is huge improvement over the current 0.6.x IMO. I fixed many existing problems and the performance difference is clear when playing 4K on my rig. The only reason I'm not merging it to trunk is that I usually use it for some period of time and see if any error pops up. Those concurrency issues are elusive.

> work for me... there must be something in SVP's log anyway

I was using an AviSynth.dll that I build myself using CMake. The dll should function exactly the same as the official release, except it does not contain any version info. The log has this line:
```
AVSF: please use Avisynth+ 3.5.0 or later
```
I wonder do you guys check version by extracting version info or use `IScriptEnvironment::CheckVersion()`?

**Comment by chainikdn** [comment]
I believe we'll need another thread for the "worker" branch and performance-related issues. And it definitely need much more testing. Again, it hangs all the time on my testing Ryzen 7 1700, and I don't see a huge perf. improvement - i.e. both "regular" and "worker" versions allow 4k/10-bit @ 24*4 = 96 fps and doesn't allow 24*5 = 120 fps. But there could be another bottleneck somewhere...

> do you guys check version by extracting version info

yep

**Comment by CrendKing** [comment]
> I believe we'll need another thread for the "worker" branch and performance-related issues.

If you have time, can you open a ticket for that? For a starter, can you pull the latest commit (even with `--force`), enable logging, trigger some hang and show me the log? Thanks!
