### ISSUE TITLE
Hang with Avisynth 3.7.1+

### ISSUE THREAD

**Issue by chainikdn** [CrendKing/avisynth_filter#70]
The video hangs right after SVP kicks in or changes script at runtime.
AVS 3.7.0 - doesn't hang at all, everything works,
3.7.1 - hangs with a green screen,
3.7.2 - hangs with a regular image (not a green screen).
It is not a complete "hang" cause it works again after manual seeking with a time bar, but if I close the player window while it hangs then the process doesn't exit.

Tested with MPC-HC and PotPlayer. Any video / format / renderer / etc - doesn't matter at all.

**Comment by CrendKing** [comment]
You are probably referring to https://github.com/CrendKing/avisynth_filter/issues/66. To use the new ConvertBits in AVSF, you have to try with `fulls` I guess?

But why is that related to SVP? Last time I check SVP still ships with AVS 3.5.1, and I thought SVP is [stuck at AVS 3.5.1](https://github.com/AviSynth/AviSynthPlus/issues/178). Whenever I use AVS 3.7 (by placing the dll to the same directory as the player), SVP never kicks in, and the event log says
```
21:24:38.410 [I]: Main: starting up SVP 4 Pro [4.5.0.213]...

21:24:38.426 [I]: Main: module 'plugins/svpflow1.dll': 4.5.0.200
21:24:38.426 [I]: Main: module 'plugins/svpflow2.dll': 4.5.0.211
21:24:38.426 [I]: Main: module 'plugins64/svpflow1.dll': 4.5.0.200
21:24:38.426 [I]: Main: module 'plugins64/svpflow2.dll': 4.5.0.212
21:24:38.426 [I]: Main: module 'plugins64/svpflow1_vs.dll': 4.5.0.200
21:24:38.426 [I]: Main: module 'plugins64/svpflow2_vs.dll': 4.5.0.211

15:49:02.843 [I]: AVSF: found new player instance
15:49:02.876 [I]: Avisynth: <redacted>\MPC-BE\avisynth.dll
15:49:02.877 [E]: AVSF: please use Avisynth+ 3.5.0 or later
15:49:33.911 [I]: AVSF: player closed
```

**Comment by CrendKing** [comment]
I added a workaround for this: https://github.com/CrendKing/avisynth_filter/actions/runs/2193050031, by feeding upstream a dummy frame. Should be sufficient to handle AVS's current situation. However, it is not future proof. If they switch to actually rely on the frame 0, there will be no way to fix, due to how DirectShow works.

**Comment by chainikdn** [comment]
> I added a workaround for this

nothing changed, still hangs

> Whenever I use AVS 3.7 (by placing the dll to the same directory as the player), SVP never kicks in, and the event log says

you probably use some custom AVS build w/o proper VersionInfo

**Comment by CrendKing** [comment]
> nothing changed, still hangs

And https://github.com/CrendKing/avisynth_filter/actions/runs/2193657724?

> you probably use some custom AVS build w/o proper VersionInfo

Literally https://github.com/AviSynth/AviSynthPlus/releases/download/v3.7.2/AviSynthPlus_3.7.2_20220317-filesonly.7z from https://github.com/AviSynth/AviSynthPlus/releases/tag/v3.7.2

**Comment by CrendKing** [comment]
> nothing changed, still hangs

I see. SVP itself works, but the injection part hangs it. I'll see what I can do.

> you probably use some custom AVS build w/o proper VersionInfo

You are correct. I used my debug build of AVS+. After switching to the official version it works.

**Comment by chainikdn** [comment]
> Is there a way to disable the version check so that I can use my debug build?

Nope. VersionInfo must contain "avisynth+" substring.

**Comment by CrendKing** [comment]
Try https://github.com/CrendKing/avisynth_filter/actions/runs/2199610106

**Comment by chainikdn** [comment]
this one crashes the player instantly, even w/o any script and/or SVP

**Comment by CrendKing** [comment]
Well, I can't repro. So you need to give me the exact steps.

**Comment by chainikdn** [comment]
there're no steps, just an instant crash

**Comment by CrendKing** [comment]
Any of the later builds work? https://github.com/CrendKing/avisynth_filter/actions

**Comment by chainikdn** [comment]
https://drive.google.com/file/d/1N_3j1ONFSCHtEVrzrvAVjsg9ytxcSxGF/view?usp=sharing

**Comment by CrendKing** [comment]
Thanks. https://github.com/CrendKing/avisynth_filter/actions/runs/2205140539 should fix it.

**Comment by chainikdn** [comment]
yes, this one finally works

**Comment by CrendKing** [comment]
Good to know. That version still has a bug about VPSF. https://github.com/CrendKing/avisynth_filter/actions/runs/2207139952 fixes it.

If you guys have time, please test. If everything works, close the ticket. I'll release a new version later.

**Comment by Nuihc88** [comment]
> Good to know. That version still has a bug about VPSF. https://github.com/CrendKing/avisynth_filter/actions/runs/2207139952 fixes it. Sorry for the regressions because there's lots of architectural changes lately.
> 
> If you guys have time, please test. If everything works, close the ticket. I'll release a new version later.

Before releasing a new version, here is something to look into...

Any builds newer than [this one](https://github.com/CrendKing/avisynth_filter/actions/runs/2178593452) won't load at all for me. Also, there is no log generated (until i revert back to an older version again).

I have briefly tested following configuration options:  
OS: Win7;
PotPlayer Portable (210707) & MPC-HC Portable & MPC-BE Portable; 
Internal Filters & LAV Filters (0.76.1);
MadVR & EVR Custom Present;
While added as 'registered filter' & 'external filter';

I don't have much time to investigate right now, but would guess that code refactoring on April 18th starting with [this commit](https://github.com/CrendKing/avisynth_filter/commit/582ca7b42283c7ca5dc8c5d13aee9e2d6bc58c34) broke Win7 support.

**Comment by CrendKing** [comment]
@Nuihc88, please create separate ticket.

**Comment by Nuihc88** [comment]
> @Nuihc88, please create separate ticket.

That's the plan; my intention was to give you a heads up about this before you release a new version, not to hijack the issue.

**Comment by CrendKing** [comment]
Several users have confirmed latest commits working form them, so this unable-to-load issue could be specific to you. Could be hardware or software environment related. We need more info to dig into, that's why I suggest a separate ticket.

I can still release a version, fix your problem, and release another version just for you later.

**Comment by CrendKing** [comment]
Feel free to re-open this if anyone found related problem.
