### ISSUE TITLE
VapourSource-how to use with a capture card or live source?

### ISSUE THREAD

**Issue by Usulyre** [CrendKing/avisynth_filter#73]
Environment

Avisynth Filter version 1.4.1 64 bit
Vapoursynth Filter version 1.4.1 64 bit
Vapoursynth version: R58 64 bit and python 3.10.4 64 bit
MPC-BE 1.5.8.6302 64 bit portable
win 10 x64

VapourSource Filter 0.2:

https://github.com/Beatrice-Raws/VapourSource/releases

Readme instructions from:

https://github.com/chikuzen/VapourSource

My script for VapourSource:

AvsFilterSource()
LoadPlugin("C:\Users\Trsula\Firefox And Internet Explorer Downloads\VapourSource_x64.dll")
VSImport("C:\Users\Trsula\Firefox And Internet Explorer Downloads\test1\smoothmotion\rifevulcan.vpy", stacked=false)

rifevulcan.vpy:

import vapoursynth as vs
core = vs.core

clip = VpsFilterSource
clip = core.resize.Bicubic(clip=clip, format=vs.RGBS, matrix_in_s="470bg", range_s="full")
clip = core.rife.RIFE(clip, model=9, multiplier=2, gpu_id=0, list_gpu=False, gpu_thread=2, tta=False, uhd=False, sc=False)
output_clip = core.resize.Bicubic(clip=clip, format=vs.YUV420P8, matrix_s="709")
output_clip.set_output()

Error:

![2022-05-02 14_30_53-Window](https://user-images.githubusercontent.com/16013427/166332143-59e5e540-3e0a-4d8e-a9e7-a03dfbefeaf3.jpg)

Using capture card or live source, however does not work with video file either. Just wanted to see if VapourSource filter would work with avisynth filter.

**Comment by CrendKing** [comment]
I don't understand. Why don't you use VPSF directly?

**Comment by Usulyre** [comment]
I have done that.

Just wanted to experiment with the VapourSource filter.

**Comment by CrendKing** [comment]
If I understand correctly, this allows you to use VapourSynth script in AviSynth environment. It won't work here because the "VpsFilterSource" is only injected to the VPSF core. VapourSource has its own VapourSynth core.

I think VapourSource is useful for offline use cases. It won't be compatible with this filter, and I don't see a reason why you want to use both. If you need to work with VapourSynth, just use VPSF.
