### ISSUE TITLE
DVD Video + LAV Filters + AVSF = green bar 16 pixel wide 

### ISSUE THREAD

**Issue by Disaer** [CrendKing/avisynth_filter#74]
### Environment
- Filter version: v1.4.1 # 460a112
- AviSynth+ version: v3.7.2
- OS: Windows 10 x64 [Version 10.0.19043.1706]
- MPC-HC 1.9.21.2 (LAV 0.76.1)
- AviSynth script: AvsFilterSource()
- [avsf.log](https://github.com/CrendKing/avisynth_filter/files/8679664/avsf.log)

### Describe the bug
When DVD resolution video (720 pixel wide) opened in MPC-HC, AVSF add 16 pixel wide green bar to it.
![2022-05-12](https://user-images.githubusercontent.com/32884204/168093069-a4307e8a-dfcf-4674-91e9-d4ad45d0cb61.png)

### To Reproduce

Just open attached sample with MPC-HC.
[VTS_06_1.zip](https://github.com/CrendKing/avisynth_filter/files/8679741/VTS_06_1.zip)

**Comment by Disaer** [comment]
Same thing happens with 720 or 1040 pixels width MP4 video.

You can create dummy MP4 video to test with ffmpeg:
`ffmpeg -f lavfi -i testsrc=duration=10:size=1040x584:rate=30 -pix_fmt yuv420p testsrc.mp4`

**Comment by CrendKing** [comment]
https://github.com/CrendKing/avisynth_filter/actions/runs/2319020509
