### ISSUE TITLE
Frame counter resets to 0 on seek

### ISSUE THREAD

**Issue by flossy83** [CrendKing/avisynth_filter#82]
The frame counter resets to 0 on seek, and this breaks a lot of things.

`Info()` to show the frame counter.

**Comment by CrendKing** [comment]
This is unavoidable in DirectShow. When player seeks, a transformation filter is incapable of telling where the seek position is w.r.t the video file. Only the source filter has that information, and it does not forward that info downstream. Think the DirectShow case as always streaming a video online whereas AviSynth handles video file locally.

You just have to deal with this limitation in your script.
