### ISSUE TITLE
vs-rife "RIFE: cuda is not available"

### ISSUE THREAD

**Issue by Usulyre** [CrendKing/avisynth_filter#86]
I followed this:

https://www.svp-team.com/forum/viewtopic.php?pid=81456#p81456

for this vapoursynth plugin: 

https://github.com/HolyWu/vs-rife

I'm getting an error "RIFE: cuda is not available" during playback with mpc-be x64 and vapoursynth filter with the one bundled with SVP4.

Can you reproduce and advise on the issue, not sure if it is related to vs-rife or not.

Just like to see if there is a fix for it.

**Comment by CrendKing** [comment]
Didn't we talk about vs-rife in https://github.com/CrendKing/avisynth_filter/issues/61? I thought you got it worked.

**Comment by Usulyre** [comment]
Yes, I tried a new installation from a different computer.

For the latest version of vs-rife, 

https://github.com/HolyWu/vs-rife/releases/tag/v3.1.0

Using vapoursynth r63 and python 3.11.4

The issue is with trt or tensorrt. Trying to install tensorrt but getting an error.

I believe the default tensorrt package included with vs-rife doesn't work for python 11.

And I was getting an error when vs-rife installtion was trying to install tensorrt 8.6.1.

I manually downloaded tensorrt 8.6.1 and installed this: 

tensorrt-8.6.1-cp311-none-win_amd64.whl

Everything else seems to be installed but when I play a video file with the filter enabled I'm still getting "cuda not available"

Can you try to install vs-rife 3.1.0 and see if everything works out? Thanks in advance.

**Comment by CrendKing** [comment]
I can get it working, though it is still too slow for real-time rendering for a 720p. The quality seems to be top tier though.

To solve "CUDA not available" error, make sure you install PyTorch using the method in https://pytorch.org/get-started/locally/, not through the transitive dependency of `vsrife`.

Since this is not an error about AVSF, I'm closing this.
