### ISSUE TITLE
Potplayer crashes at close when using filter while SVP is inactive 

### ISSUE THREAD

**Issue by chorong761** [CrendKing/avisynth_filter#9]
Potplayer will crash when I close the player w/ filter v0.6.1 (avs+ 3.5, 3.6, 3.6.1 same issue) if SVP is inactive at the time of closing.

Downgrading to filter v0.6.0 seems to have solved the issue, possibly a bug?

**Comment by CrendKing** [comment]
What do you mean "if SVP is inactive at the time of closing" exactly? Having SVP disabled or conditionally not apply a profile? I need more detailed steps to reproduce the issue.

So far I tried

1. Just using the filter in PotPlayer and load SVP plugins. Everything works.
2. Let SVP take over the control in PotPlayer. Everything works.

**Comment by chorong761** [comment]
what i mean is just adding the the avisynth filter in potplayer and setting it to perfer, then play a video with SVP off. Crashes with that error when I close the player. I have the same problem on 2 different computers

**Comment by CrendKing** [comment]
OK, I managed to reproduce the crash. Question: do you use madVR? If yes, can you confirm you use madVR by selecting "Madish Video Renderer" in the "Video Renderer" dropdown? If yes again, try the following:

1. Select a different renderer, e.g. EVR
2. After 1, go to Settings, Filter Control, add madVR64.ax, set to prefer. Reopen the video, and confirm you are using madVR this way by going right click -> Filters (both "madVR" and "AviSynth Filter" should be there, and make sure it's not "Madish Video Renderer")

If again, in both cases there is no more crash, then we are on the same page. Let me know your result.

**Comment by chorong761** [comment]
Yes, I do use madvr and it is selected via the video render list

1. EVR doesnt crash
2. did that, shows madvr and avs filter, doesnt crash

so yes we are on the same page!

**Comment by CrendKing** [comment]
Try [avisynth_filter_64.zip](https://github.com/CrendKing/avisynth_filter/files/5381441/avisynth_filter_64.zip)

As to why this only happens to this specific setup, I think it has something to do with how PotPlayer loads and uses madVR. When exiting, it probably unloads modules too early too fast. I recall years ago when I use PotPlayer I notice weirdness with this setup. The workaround setup also has its own issues, so I do not recommend.

**Comment by chorong761** [comment]
Just tried that one you attached and it works 👍

**Comment by chainikdn** [comment]
Again, PotPlayer sometimes crashes with 0.8.1, mostly when switching to another video in playlist and with LAV Video decoder in use. Last lines in the log:
> T   6912 @    33769: Frame handler start BeginFlush()
> T   6912 @    33769: Frame handler cleanup after stop threads
I know it crashes on a `t.join();` line but I can't provide full callstack cause I'm unable to attach debugger to the PotPlayer process for some reason oO

**Comment by CrendKing** [comment]
@chainikdn How does `t.join()` ever crash? You mean hang? Mind if creating a new issue to track?

**Comment by chainikdn** [comment]
> How does `t.join()` ever crash?

I just put a log line before and after join() call... this obviously doesn't mean that join() is crashing, but the output thread is crashing on termination

**Comment by CrendKing** [comment]
Here's what I tried:

1. Download fresh new PotPlayer64.
2. Add LAV and AVSF to to. AVS script set to have SVP and prefetcher activated. FRC to 60fps.
3. Add a bunch videos to playlist.
4. Play and switch. Sometimes seek.

No crash at all. This is probably another hard-to-reproduce issue. You need to open an issue and detail all the info. Or try a few things (reset PotPlayer settings, minimal avs script, different videos, etc) yourself.
