### ISSUE TITLE
TFM with Avisynth Filter make the Player to not start playing.

### ISSUE THREAD

**Issue by Samus421** [CrendKing/avisynth_filter#93]
Hello,

I'm trying to use a very simple script to perform on the fly IVTC but I have a small issue related to TFM with Avisynth Filter. Each time I have TFM in the script, the player is blocked on the initial black screen and do not start to play. I have to make a small jump ( like 5 seconds) and then the video start to play fine, but switching Play/Pause do not work.  Using TDecimate alone, I have not a such issue and the video automatically starts from the first frame as expected.
I use the latest version of Avisynth+ (3.7.3), Avisynth Filter (1.4.6),  TIVTC (1.0.29) and TDeint(1.9.7), on my windows 10 (up to date) system. I had this issue with the latest MPC-HC (2.3.3) and J River Media Player (MC30), using Madvr (0.97) or Evr-custom video renderer with the latest  Lav Audio/Video/Splitter. Everything (filters, players and system) is in 64bits.

Here the very simple script I use:
AvsFilterSource()
fps = Round(FrameRate())
if (fps > 29) {	
	tfm().tdecimate()
} else {
    AvsFilterDisconnect()
}

**Comment by CrendKing** [comment]
I can reproduce this fairly consistently with MPC Video Renderer, but can't with EVR-Custom at all.

**Comment by Samus421** [comment]
To produce a log, I need a debug version, right? Where could I find one compiled?

I have a second PC (still in windows 10 and same setup as my desktop one) and the situation is exactly the same.

**Comment by CrendKing** [comment]
> I need a debug version, right?

No. Just follow https://github.com/CrendKing/avisynth_filter/wiki/How-to-enable-logging

**Comment by Samus421** [comment]
Sorry, I should have checked your github.
So, here two log files : 
- for Log1.log I close the player without any jump so the file never start. Interesting point, even if the windows is closed, the mpchc.exe process still hang in background and I have to force it to close via Task Manager. 
- For Log2.log, I made a slight jump (5 seconds) and the file start playing. Unfortunately, in around 3 minutes, I have huge drop of framerate (4/5fps instead of 24), Evr-CP stutter and Madvr seems to crash even if the CPU is still around 25%. It seems that is always around the same frames so it seems to be the script.
- 
[Log1.log](https://github.com/user-attachments/files/16468788/Log1.log)
[Log2.log](https://github.com/user-attachments/files/16468790/Log2.log)

**Comment by CrendKing** [comment]
From your log files, I can see the filter receives 2 frames from upstream, stored them, but downstream never requested those frames. But since I can't reproduce this behavior, you may try to tweak the [configs](https://github.com/CrendKing/avisynth_filter/wiki/Configuration) see if improve. For example, if you increase `InitialSrcBuffer`, you will see more initial frames stored.

Also, could you try the artifact of https://github.com/CrendKing/avisynth_filter/actions/runs/10225291367?

**Comment by Samus421** [comment]
You're right, I put InitialSrcBuffer to 12 (I will test later which smaller value could works) and now the player (mpc+evr cp or J river+madvr) start as required!
Thank you very much for your support!
Now I have to work on the script. So far, put slow on TFM to 0 seems to fix the framedrop issue but more test seems required.
Again, thanks!
