### ISSUE TITLE
AviSynth Filter support for old AviSynth FrameServer 2.6.0?

### ISSUE THREAD

**Issue by HUNGDUNG7805** [CrendKing/avisynth_filter#94]
I want to ask if there are any AviSynth Filter support the old AviSynth FrameServer 2.6.0, and if you have a plan on making one in the future, since some older version of SVP just wont work with AviSynth Plus. Thanks

**Comment by CrendKing** [comment]
Most likely not. 2.6 is officially deprecated. I would suggest you to update your copy of SVP.
